version: "3.9"

services:
  app:
    container_name: hydro-report-app
    build:
      context: .
    image: hydro-report:latest
    env_file:
      - .env
    volumes:
      - ./.cache:/app/.cache
      - ./public:/app/public
      - /etc/letsencrypt/live/thuydien.thebien.net/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/thuydien.thebien.net/privkey.pem:/etc/nginx/certs/privkey.pem:ro
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
